[project]
name = "renardo"
version = "0.9.0"
description = "Python livecoding environment - New fork of FoxDot"
authors = [
    {name = "Élie Gavoty", email="eliegavoty@free.fr"},
]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.8"

keywords = ["algorithmic music", "livecoding", "algorave", "supercollider"]

classifiers = [
    "Topic :: Software Development"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages=[
    'renardo',
    'renardo.lib.Code',
    'renardo.lib.Custom',
    'renardo.lib.Extensions',
    'renardo.lib.Extensions.VRender',
    'renardo.lib.Extensions.SonicPi',
    'renardo.lib.Workspace',
    'renardo.lib.Workspace.Simple',
    'renardo.lib.EspGrid',
    'renardo.lib.Effects',
    'renardo.lib.Patterns',
    'renardo.lib.SCLang',
    'renardo.lib.Settings',
    'renardo.lib.Utils'
]