name: Create release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create prerelease
        if: contains( github.ref_name, 'dev' )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        #|
          # gh release create "$tag" \
          #    --repo="$GITHUB_REPOSITORY" \
          #    --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
          #    --generate-notes
        run: |
          echo "${GITHUB_REPOSITORY#*/} ${tag#v}"
